name: Deploy to Hostinger

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: portfolio
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'portfolio/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular (production)
        run: npm run build --if-present

      - name: Add .htaccess for SPA routing
        run: |
          DIST_DIR="dist/portfolio/browser"
          mkdir -p "$DIST_DIR"
          cat > "$DIST_DIR/.htaccess" <<'EOF'
          <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteBase /
            RewriteCond %{REQUEST_FILENAME} -f [OR]
            RewriteCond %{REQUEST_FILENAME} -d
            RewriteRule ^ - [L]
            RewriteRule ^ index.html [L]
          </IfModule>
          EOF

      - name: Validate required secrets
        env:
          S_HOST: ${{ secrets.HOSTINGER_HOST }}
          S_USER: ${{ secrets.HOSTINGER_USERNAME }}
          S_PASS: ${{ secrets.HOSTINGER_PASSWORD }}
          S_TARGET: ${{ secrets.HOSTINGER_TARGET }}
        run: |
          missing=()
          [ -z "$S_HOST" ] && missing+=("HOSTINGER_HOST")
          [ -z "$S_USER" ] && missing+=("HOSTINGER_USERNAME")
          [ -z "$S_PASS" ] && missing+=("HOSTINGER_PASSWORD")
          [ -z "$S_TARGET" ] && missing+=("HOSTINGER_TARGET")
          if [ ${#missing[@]} -ne 0 ]; then
            echo "Secrets manquants: ${missing[*]}"
            exit 1
          fi
          
      - name: Deploy via FTPS to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          protocol: ftps
          # port: ${{ secrets.HOSTINGER_PORT }}   # optionnel (par défaut 21 pour FTPS)
          local-dir: portfolio/dist/portfolio/browser/
          server-dir: ${{ secrets.HOSTINGER_TARGET }}
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/*.map
